env:
  # You must encrypt your DoltHub token using the Cirrus CI web interface
  # https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables
  DOLTHUB_TOKEN: ENCRYPTED[f54e9df42ab5dd76b364016cdb1db0eb280fda231dc3591e3a5da3330fb5a04bfa3b318cd84ddbcb6f0575e12291cd1d]
  SQLITE_ZIP_URL: "https://www.kaggle.com/api/v1/datasets/download/justsahil/imdb-sql"
  DOLT_REPO_NAME: "sahil/imdb"
  SQLITE_FILENAME: "imdb.sqlite"

task:
  name: Update DoltHub Database
  # Using a Python base image since sqlite3-to-mysql is a Python package
  container:
    image: python:latest
    use_in_memory_disk: true
    cpu: 8
    memory: 32G

  install_dependencies_script:
    - apt-get update && apt-get install -y unzip sudo curl
    # Install Dolt using the official installation script
    - curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash
    # Install the SQLite to MySQL conversion tool
    - pip install sqlite3-to-mysql

  download_and_extract_script:
    - wget -O data.zip $SQLITE_ZIP_URL
    - unzip data.zip -d extracted_data/
    - rm data.zip

  dolt_upload_script:
    # 1. Configure Dolt
    - dolt config --global --set user.email "ci-bot@example.com"
    - dolt config --global --set user.name "Cirrus CI Bot"
    # Authenticate with DoltHub using the provided token 
    - echo "$DOLTHUB_TOKEN" | dolt creds import

    # 2. Initialize Dolt Repository
    - mkdir dolt_workspace
    - cd dolt_workspace
    - dolt init
    - dolt remote add origin $DOLT_REPO_NAME

    # 3. Start Dolt SQL Server in the background 
    - dolt sql-server --host 0.0.0.0 --port 3306 &
    - DOLT_PID=$!
    # Wait briefly to ensure the server starts properly
    - sleep 5

    # 4. Import SQLite data into the Dolt server
    # This mirrors the Justfile behavior of piping the unzipped sqlite file via localhost
    - |
      sqlite3mysql --sqlite-file ../extracted_data/$SQLITE_FILENAME \
          --mysql-database $(basename $PWD) \
          --mysql-user root \
          --mysql-password "" \
          --mysql-host localhost \
          --mysql-port 3306

    # 5. Stop the Dolt SQL server
    - kill $DOLT_PID
    - sleep 5

    # 6. Commit and Push to DoltHub
    - dolt add .
    - dolt commit -m "Automated SQLite data import via Cirrus CI"
    # Pushes to the main branch; force is used in the original repo to overwrite
    - dolt push --force origin main
