env:
  # You must encrypt your DoltHub token using the Cirrus CI web interface
  # https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables
  DOLTHUB_TOKEN: ENCRYPTED[your_encrypted_token_here]
  DUCKDB_ZIP_URL: "https://example.com/path/to/your/database.zip"
  DOLT_REPO_NAME: "your_username/your_repo_name"
  DUCKDB_FILENAME: "database.duckdb" # Name of the file after unzipping

task:
  name: Update DoltHub Database
  container:
    image: ubuntu:latest

  install_dependencies_script:
    - apt-get update && apt-get install -y unzip wget curl sudo
    
    # Install Dolt
    - curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | sudo bash
    
    # Install DuckDB CLI (v1.1.3 based on your .tool-versions)
    - wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip
    - unzip duckdb_cli-linux-amd64.zip -d /usr/local/bin/
    - rm duckdb_cli-linux-amd64.zip

  download_and_extract_script:
    - wget -O data.zip $DUCKDB_ZIP_URL
    - unzip data.zip -d extracted_data/

  dolt_upload_script:
    # 1. Configure Dolt
    - dolt config --global --set user.email "ci-bot@example.com"
    - dolt config --global --set user.name "Cirrus CI Bot"
    - echo "$DOLTHUB_TOKEN" | dolt creds import

    # 2. Initialize Dolt Repository
    - mkdir dolt_workspace
    - cd dolt_workspace
    - dolt init
    - dolt remote add origin $DOLT_REPO_NAME

    # 3. Start Dolt SQL Server in the background
    # Using 127.0.0.1 specifically so DuckDB's MySQL extension routes via TCP properly
    - dolt sql-server --host 127.0.0.1 --port 3306 &
    - DOLT_PID=$!
    - sleep 5 # Wait briefly to ensure server starts

    # 4. Import DuckDB data into Dolt using the MySQL extension
    # We pass a heredoc script into the DuckDB CLI
    - |
      DB_NAME=$(basename $PWD)
      duckdb ../extracted_data/$DUCKDB_FILENAME <<EOF
      INSTALL mysql;
      LOAD mysql;
      
      -- Attach the local Dolt server as a MySQL database
      ATTACH 'host=127.0.0.1 port=3306 user=root database=$DB_NAME' AS dolt_db (TYPE MYSQL);
      
      -- Copy the table from DuckDB to Dolt. 
      -- Change 'projects' to match the specific tables in your DuckDB file if necessary.
      CREATE TABLE dolt_db.projects AS SELECT * FROM projects;
      EOF

    # 5. Stop the Dolt SQL server
    - kill $DOLT_PID

    # 6. Commit and Push to DoltHub
    - dolt add .
    - dolt commit -m "Automated DuckDB data import via Cirrus CI"
    - dolt push --force origin main
